#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

<<<<<<<< HEAD:drivers/soc/mediatek/devapc/mt6739/Makefile
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
obj-y += devapc.o
========
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += DW9800VAF.o


>>>>>>>> 32022887f842 (Kernel: Xiaomi kernel changes for Redmi Note 11S Android S):drivers/misc/mediatek/lens/main/common/dw9800vaf/Makefile
